language: python

sudo: false

python:
  - "2.7"

install:
  - pip install git+https://github.com/colab/colab/
  - pip install flake8 coveralls
  - pip install .

script:
  - python setup.py test
  - flake8 src/colab_noosfero
  - flake8 tests

after_success:
  - coveralls
